name: depolyment to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name : deplotment every to the staging cluster
    steps:
      - run: |
          echo "Deploying to staging cluster this is the echo here "
          echo "${{secrets.SSH_DIGITAL_OCEAN_KEY}}" &> ~/ssh_key
          chmod 700 ~/ssh_key
          ssh -i ~/ssh_key -o StrictHostKeyChecking=no root@143.110.252.78  -t "bash -l -c 'cd turbo-repo &&
          git pull &&
          npm install -g pnpm &&
          pnpm build &&
          pm2 restart all
          '"
